driver_upper:
  ros__parameters:
    pro_motors: [4, 5, 11, 12, 30, 31] #Motor ids that are the dynamixel pro motors
    xm_motors: [1, 2, 3, 6, 7, 8, 9, 10, 13, 14, 15, 16, 17, 21, 22, 23, 24] #Motor ids that are dynamixel xm540
    usb_device: "FT583SPF" #USB Device to be ran on
    usb_baudrate: 1000000 #Baudrate, probably wont be changed