driver_upper:
#Negative one at start of list means that will be ignored on load
  ros__parameters:
    pro_motors: [-1] #Motor ids that are the dynamixel pro motors
    xm_motors: [1,2,3,4,5,6,7,11,12,13,14,15,16,17] #Motor ids that are dynamixel xm540
    usb_device: "FT583SPF" #USB Device to be ran on
    usb_baudrate: 1000000 #Baudrate, probably wont be changed