#This combines to define our path for the topics
system: "telebot" #This is running on the telebot
level: "L_1" #The level of the system
subsystem: "motion" #The system name, generally should be the package name

multiplexer:
  ros__parameters:
    control_sources:
      minibot_control: ["topic1,topic2"]
      gui_control: ["eg1,eg2"]
